#!/bin/bash

CURRENT_DIR=`pwd`


# install dependencies --------------------------------------------------------

#echo "deb http://archive.ubuntu.com/ubuntu precise main universe" > /etc/apt/sources.list
#echo "deb http://ppa.launchpad.net/rethinkdb/ppa/ubuntu precise main" >> /etc/apt/sources.list
apt-get -y update
apt-get -y upgrade

apt-get -y --force-yes install vim

apt-get -y --force-yes install python-ldap 
apt-get -y --force-yes install nginx
apt-get -y --force-yes install expect
apt-get -y --force-yes install git
apt-get -y --force-yes install memcached
apt-get -y --force-yes install sqlite3
apt-get -y --force-yes install libcairo2
apt-get -y --force-yes install libcairo2-dev
apt-get -y --force-yes install pkg-config
apt-get -y --force-yes install supervisor

apt-get -y --force-yes install python-cairo
apt-get -y --force-yes install python-django 
apt-get -y --force-yes install python-django-tagging 
apt-get -y --force-yes install python-flup
apt-get -y --force-yes install python-simplejson 
apt-get -y --force-yes install python-memcache 
apt-get -y --force-yes install python-pysqlite2
apt-get -y --force-yes install python-twisted
apt-get -y --force-yes install python-support 
apt-get -y --force-yes install python-pip 
apt-get -y --force-yes install gunicorn 
apt-get -y --force-yes install python 
apt-get -y --force-yes install g++ 
apt-get -y --force-yes install make 
apt-get -y --force-yes install checkinstall

pip install django==1.3
pip install python-memcached==1.53
pip install django-tagging==0.3.1
pip install whisper==0.9.12
#pip install twisted==11.1.0
pip install txAMQP==0.6.2

# NODE
cd /usr/local/src
src=$(mktemp -d) && cd $src
wget -N http://nodejs.org/dist/node-latest.tar.gz
tar xzvf node-latest.tar.gz && cd node-v*
./configure
fakeroot checkinstall -y --install=no --pkgversion $(echo $(pwd) | sed -n -re's/.+node-v(.+)$/\1/p') make -j$(($(nproc)+1)) install
dpkg -i node_*


# get source code -------------------------------------------------------------
cd /usr/local/src
git clone https://github.com/graphite-project/graphite-web.git
cd graphite-web
git checkout 0.9.12
python ./setup.py install

cd /usr/local/src
git clone https://github.com/graphite-project/whisper.git
cd whisper
git checkout 0.9.12
python ./setup.py install

cd /usr/local/src
git clone https://github.com/graphite-project/carbon.git
cd carbon
git checkout 0.9.12
python ./setup.py install

cd /usr/bin
git clone https://github.com/etsy/statsd.git

# configure django admin user -------------------------------------------------
cat << EOF > /tmp/graphite_syncdb
#!/usr/bin/expect

set timeout -1
spawn python /opt/graphite/webapp/graphite/manage.py syncdb
expect "Would you like to create one now" {
  send "yes\n"
}
expect "Username *:" {
  send "root\n"
}
expect "E-mail address:" {
  send "lyddonb@gmail.com\n"
}
expect "Password:" {
  send "root\n"
}
expect "Password *:" {
  send "root\n"
}
expect "Superuser created successfully"
EOF

chmod 775 /tmp/graphite_syncdb
/tmp/graphite_syncdb
rm /tmp/graphite_syncdb

cd $CURRENT_DIR

# configure graphite
cp configs/local_settings.py /opt/graphite/webapp/graphite/local_settings.py
cp /opt/graphite/conf/graphite.wsgi.example /opt/graphite/webapp/graphite/graphite_wsgi.py
chown -R www-data /opt/graphite/webapp
chown -R www-data /opt/graphite/storage
chown -R www-data /usr/bin/statsd
chmod 0775 /opt/graphite/storage /opt/graphite/storage/whisper
chmod 0664 /opt/graphite/storage/graphite.db

# configure carbon ------------------------------------------------------------
cp configs/carbon.conf /opt/graphite/conf/carbon.conf
cp configs/storage-schemas.conf /opt/graphite/conf/storage-schemas.conf
cp configs/storage-aggregation.conf /opt/graphite/conf/storage-aggregation.conf
cp configs/nginx.conf /etc/nginx/nginx.conf
cp configs/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
cp config.js /usr/bin/statsd/config.js


mkdir -p /var/log/graphite
mkdir -p /var/log/nginx
mkdir -p /var/log/carbon

# NOT SURE IF NEEDED YET
unlink /var/run/supervisor.sock

/usr/bin/supervisord
